### ISSUE TITLE
大佬，想跟您交流下

### ISSUE THREAD

**Issue by flawlessv** [nonhana/Date-Blind-Box-Admin-Server#1]
请问这个前端有木有，我vx：qwq-----7，可以交个朋友嘛

**Comment by nonhana** [comment]
啊，这个是模板啦，不是我开发的，

**Comment by nonhana** [comment]
![https://github.com/kongyijilafumi/react-ant-admin-ts](https://github.com/kongyijilafumi/react-ant-admin-ts)，就是这个模板，你可以自己去参考一下~

**Comment by flawlessv** [comment]
好的 谢谢哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: non_hana ***@***.***&gt;
发送时间: 2024年1月20日 22:07
收件人: nonhana/Date-Blind-Box-Admin-Server ***@***.***&gt;
抄送: qwq77 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [nonhana/Date-Blind-Box-Admin-Server] 大佬，想跟您交流下 (Issue #1)





 
，就是这个模板，你可以自己去参考一下~

**Comment by nonhana** [comment]
嗯嗯，没事
